/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:53c86589-508d-41bc-9e33-4ae525d1073f',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_jEekDEyDc',
  aws_user_pools_web_client_id: '49qvqf4g72nqt9qfpg8adccfe7',
  oauth: {},
};

export default awsmobile;
